{% set name = "xicam.xpcs" %}
{% set version = "1.2.0" %}
{% set sha256 = "5ecc1b4b4493eaf063d2663cd64a9780a9ee38cd4e67dda7f989eaa9cc79768f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/synchrotrons/Xi-cam.XPCS/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - event-model >=1.13.0b4
    - scikit-image
    - scipy
    - xicam.plugins
    - xicam.saxs

# Commenting out since it's trying to pull xicam.args. Will be uncommented once
# xicam.args is a separate package.
# test:
#   imports:
#     - xicam.XPCS

about:
  home: https://github.com/synchrotrons/Xi-cam.XPCS
  license: BSD 3-clause
  license_file: LICENSE.md
  summary: XPCS plugin for Xi-cam
